local factorycreate = require( "factorycreate.factorycreate" )


-- methods ------------------------
function init( self )
	msg.post( ".", "acquire_input_focus" )
	msg.post( "@render:", "use_fixed_fit_projection", { near = -1, far = 1 } )
end


function on_input( self, action_id, action )
	if action_id == hash( "touch" ) and action.pressed then
		local pos = vmath.vector3( action.x, action.y, .5 )
		factorycreate( "/test#objectfactory", pos, nil, { foo = "Hello World...!" } )
	end
end



